// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Source_Serif_4 } from "next/font/google";
import localFont from "next/font/local";
import Header from "./components/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sourceSerif4 = Source_Serif_4({
  variable: "--font-source-serif-4",
  subsets: ["latin"],
  weight: ["400", "600"], // 👈 important for headings
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
});

export const playfairDisplay = localFont({
  src: [
    {
      path: "./fonts/Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "PhiliFinds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`
        ${geistSans.variable} 
        ${geistMono.variable} 
        ${poppins.variable} 
        ${sourceSerif4}   // 👈 ADD THIS
        ${playfairDisplay.variable} 
        h-full antialiased
      `}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}